#!/bin/sh
# When addressing commit messages follow these rules:
# Title: Summary, imperative, start upper case, don't end with a period
# No more than 50 chars. #### 50 chars is here:  #
# Remember blank line between title and body.
# Body: Explain *what* and *why* (not *how*). Include task ID (Jira issue).
# Wrap at 72 chars. ################################## which is here:  #
# Special instructions, testing steps, rake, etc
# At the end: Include Co-authored-by for all contributors.
# Include at least one empty line before it. Format:
# Co-authored-by: name <user@users.noreply.github.com>


# Skip hooks Use either -n or --no-verify


# ticket DDDS-18: Terraform fmt
# Change to the terraform directory
cd terraform || {
  echo "Directory 'terraform' not found. Aborting push."
  exit 1
}

# Run terraform fmt in check mode recursively inside /terraform
if ! terraform fmt -check -recursive; then
  echo "Terraform files in /terraform are not properly formatted. Please run 'terraform fmt' in the /terraform directory."
  exit 1  # Abort the push
fi

# Formatting is good, allow push
exit 0